name: Python Test, Build and Deploy on Master Merge (TAR archive)

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - run: pip install -r requirements.txt || true

      - run: python -m unittest discover -s test -p "*.py" --verbose

  build-and-publish:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build source distribution (.tar.gz)
        run: |
          python -m build --sdist

      - name: Upload built sdist as artifact
        uses: actions/upload-artifact@v4
        with:
          name: sdist-dist
          path: dist/*.tar.gz

      - name: Upload sdist to Gemfury
        env:
          GEMFURY_API_TOKEN: ${{ secrets.GEMFURY_API_TOKEN }}
        run: |
          FILE=$(ls dist/*.tar.gz | head -n 1)
          curl -F package=@"$FILE" https://push.fury.io/omolchanov/ \
            -H "Authorization: $GEMFURY_API_TOKEN"