name: Python Test, Build and Deploy on Master Merge (whl package)

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install test dependencies
        run: pip install -r requirements.txt || true  # optional if you use requirements.txt

      - name: Run unittest tests
        run: python -m unittest discover -s test -p "*.py" --verbose

  build:
    needs: test  # Wait until tests pass
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build wheel setuptools twine

      - name: Build wheel
        run: python -m build

      - name: Upload wheel to Gemfury
        env:
          GEMFURY_API_TOKEN: ${{ secrets.GEMFURY_API_TOKEN }}
        run: |
          ls dist/
          WHEEL_FILE=$(ls dist/*.whl)
          echo "Uploading $WHEEL_FILE"
          curl -H "Authorization: Bearer $GEMFURY_API_TOKEN" -F package=@"$WHEEL_FILE" https://push.fury.io/omolchanov/



  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download wheel artifact
        uses: actions/download-artifact@v4
        with:
          name: wheel-dist
          path: dist/

      - name: Install twine
        run: python -m pip install --upgrade twine

      - name: Upload to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload dist/* --verbose
      
