name: Python Test on Master Merge

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Run unittest tests
        run: |
          python -m unittest discover -s test -p "*.py" --verbose

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build wheel setuptools
          
      - name: Build wheel
        run: python -m build

      - name: Upload built artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
