name: Python Test, Build and Deploy on Master Merge (whl package)

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - run: pip install -r requirements.txt || true

      - run: python -m unittest discover -s test -p "*.py" --verbose

  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      wheel-file: ${{ steps.get_wheel.outputs.wheel_file }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - run: |
          python -m pip install --upgrade pip
          pip install build wheel setuptools twine

      - run: python -m build

      # Capture wheel filename in output
      - id: get_wheel
        run: echo "wheel_file=$(ls dist/*.whl)" >> $GITHUB_OUTPUT

      - name: Upload wheel as artifact
        uses: actions/upload-artifact@v3
        with:
          name: wheel-dist
          path: dist/*.whl

      - name: Upload wheel to Gemfury
        env:
          GEMFURY_API_TOKEN: ${{ secrets.GEMFURY_API_TOKEN }}
        run: |
          WHEEL_FILE=$(ls dist/*.whl)
          echo "Uploading $WHEEL_FILE to Gemfury"
          curl -H "Authorization: Bearer $GEMFURY_API_TOKEN" -F package=@"$WHEEL_FILE" https://push.fury.io/omolchanov/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: wheel-dist
          path: dist

      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - run: python -m pip install --upgrade twine

      - name: Upload to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/* --verbose
